### ISSUE TITLE
Beta release todo list

### ISSUE THREAD

**Issue by mattvb91** [mattvb91/Subterminal-iOS#1]
- [ ] Dropzones visited count on dashboard
- [ ] Disable spellchecker on dropzone select for skydive entry
- [ ] Allow selecting rig on skydive form
- [x] Implement empty tableview 
- [ ] Gear dropdown to choose adding suit or rig
- [ ] Select rigs on BASE jump entry
- [x] BASE rig form + Dropdown for adding rigs/suits
